import bcrypt from 'bcryptjs'

const data = {
    users: [
      {
        name: 'selmi',
        email: 'admin@example.com',
        password: bcrypt.hashSync('123456'),
        isAdmin: true,
      },
      {
        name: 'ameni',
        email: 'user@example.com',
        password: bcrypt.hashSync('123456'),
        isAdmin: false,
      },
    ],
    products: [
      {
        _id :1 ,
        name: 'laptop1',
        slug: 'lap1' ,
        category: 'Laptops',
        image: '/images/p1.jpg', // 679px × 829px
        price: 120,
        countInStock: 10,
        brand: 'HP',
        rating: 4,
        nbRating: 168 ,
        description: 'Acer Aspire 1, 15.6" FHD, ICD N4020, 4GB RAM, 128GB eMMC, Windows 10S + Office 365, Black, A115-31-C9K3',
        ram : "8 GB" ,
        os	: "Windows 10 Home" ,
        CPU : "Core i5" ,
        screen : "size	19 Inches" ,
        disk : "HDD 7200 rpm" ,
      },
      {
        _id :2 ,
        name: 'desktop1',
        slug: 'des1' ,
        category: 'Desktops',
        image: '/images/p2.jpg', // 679px × 829px
        price: 120,
        countInStock: 10,
        brand: 'HP',
        rating: 3.5,
        nbRating: 168 ,
        description: 'Acer Aspire 1, 15.6" FHD, ICD N4020, 4GB RAM, 128GB eMMC, Windows 10S + Office 365, Black, A115-31-C9K3',
        ram : "8 GB" ,
        os	: "Windows 10 Home" ,
        CPU : "Core i5" ,
        screen : "size	19 Inches" ,
        disk : "HDD 7200 rpm" ,
      },
      {
        _id :3 ,
        name: 'smatphone1',
        slug: 'sma1' ,
        category: 'Smartphones',
        image: '/images/p3.jpg', // 679px × 829px
        price: 120,
        countInStock: 10,
        brand: 'HP',
        rating: 2.5,
        nbRating: 168 ,
        description: 'Acer Aspire 1, 15.6" FHD, ICD N4020, 4GB RAM, 128GB eMMC, Windows 10S + Office 365, Black, A115-31-C9K3',
        ram : "8 GB" ,
        os	: "Windows 10 Home" ,
        CPU : "Core i5" ,
        screen : "size	19 Inches" ,
        disk : "HDD 7200 rpm" ,
      },
      {
        _id :4 ,
        name: 'monitor1',
        slug: 'moni1' ,
        category: 'Monitors',
        image: '/images/p4.jpg', // 679px × 829px
        price: 120,
        countInStock: 10,
        brand: 'HP',
        rating: 4.5,
        nbRating: 168 ,
        description: 'Acer Aspire 1, 15.6" FHD, ICD N4020, 4GB RAM, 128GB eMMC, Windows 10S + Office 365, Black, A115-31-C9K3',
        ram : "8 GB" ,
        os	: "Windows 10 Home" ,
        CPU : "Core i5" ,
        screen : "size	19 Inches" ,
        disk : "HDD 7200 rpm" ,
      },
    ],
  };
  export default data;